### PR TITLE
base: Add support for DiracSound FX

### PR DESCRIPTION
**Pull request by UtsavBalar1231**
[@AgentFabulous - POSP]
- Ported out of MIUI framework, cleaned up
- Added some missing methods
- Add optional logging

Signed-off-by: Kshitij Gupta <kshitijgm@gmail.com>
Change-Id: I533898dbb408d20779c655d2f3d2c2855cafc864

### CODE REVIEW

**Comment by UtsavBalar1231** [comment]
Yay

**Comment by Chityanj** [comment]
@UtsavisGreat tested?

**Review by Chityanj — COMMENTED** [review]
Didn't work

**Comment by Verevka** [comment]
I have works

**Comment by Chityanj** [comment]
Bitch utsav

**Comment by SpectoMan** [comment]
Wadu wadu waduhek

**Comment by SpectoMan** [comment]
@SpectoMan Wadu wadu waduhek

**Comment by SpectoMan** [comment]
@Giovix92 @chityanjsharma

**Pull request closed without merging**
